/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cityhall.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/cityhall.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-25.918, 3.933, -259.548]} rotation={[-1.813, -0.832, -1.028]} scale={[3.554, 4.525, 4.525]}>
          <group name="056edf7cea0c4eaab1d75dfcd6ed0260fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="BUILDING" position={[0.865, 0, -0.489]} scale={0.875}>
                <group name="AIR_CON">
                  <mesh name="AIR_CON_standardSurface1_0" geometry={nodes.AIR_CON_standardSurface1_0.geometry} material={materials.standardSurface1} />
                </group>
                <group name="SIGNS">
                  <mesh name="SIGNS_standardSurface1_0" geometry={nodes.SIGNS_standardSurface1_0.geometry} material={materials.standardSurface1} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" position={[99.792, 3.732, -329.779]} rotation={[-1.813, -0.832, -1.028]} scale={[2.618, 3.334, 3.334]}>
          <group name="056edf7cea0c4eaab1d75dfcd6ed0260fbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="BUILDING001" position={[0.865, 0, -0.489]} scale={0.875}>
                <group name="AIR_CON001" />
                <group name="SIGNS001">
                  <mesh name="SIGNS_standardSurface1_0001" geometry={nodes.SIGNS_standardSurface1_0001.geometry} material={materials.standardSurface1} />
                </group>
                <mesh name="BUILDING_standardSurface1_0001" geometry={nodes.BUILDING_standardSurface1_0001.geometry} material={materials.standardSurface1} position={[-6.359, 17.735, 3.064]} />
              </group>
            </group>
          </group>
        </group>
        <group name="BézierCurve" position={[17.361, 0, 43.727]} />
        <group name="Sketchfab_model002" position={[-135.885, 109.112, -148.273]} rotation={[-1.813, -0.832, -1.028]} scale={[10.597, 13.493, 13.493]} />
        <group name="Sketchfab_model003" position={[238.956, 108.512, -357.687]} rotation={[-1.813, -0.832, -1.028]} scale={[7.808, 9.942, 9.942]} />
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={90.712} position={[17.361, 7.694, -310.575]} rotation={[1.465, 0.141, -1.057]} />
        <group name="Residential_Buildings_009_Cube004" position={[-10.409, 3.933, -323.858]} rotation={[Math.PI / 2, 0, 1.796]} scale={[1.161, 1.161, 0.513]}>
          <mesh name="Residential_Buildings_009_Cube004_1" geometry={nodes.Residential_Buildings_009_Cube004_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube004_2" geometry={nodes.Residential_Buildings_009_Cube004_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube001" position={[36.454, 3.933, -267.018]} rotation={[1.486, 0.274, 1.795]} scale={1.704}>
          <mesh name="Residential_Buildings_009_Cube001_1" geometry={nodes.Residential_Buildings_009_Cube001_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube001_2" geometry={nodes.Residential_Buildings_009_Cube001_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_006_Cube014" position={[-52.11, -3.108, -297.666]} rotation={[Math.PI / 2, 0, 0.192]} scale={3.026}>
          <mesh name="Residential_Buildings_006_Cube014_1" geometry={nodes.Residential_Buildings_006_Cube014_1.geometry} material={materials['ground.005']} />
          <mesh name="Residential_Buildings_006_Cube014_2" geometry={nodes.Residential_Buildings_006_Cube014_2.geometry} material={materials['hotel_glas.005']} />
        </group>
        <group name="Residential_Buildings_009_Cube002" position={[145.292, -15.178, -344.741]} rotation={[-1.701, -0.04, 2.242]} scale={[-1.945, -8.171, -1.95]}>
          <mesh name="Residential_Buildings_009_Cube002_1" geometry={nodes.Residential_Buildings_009_Cube002_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube002_2" geometry={nodes.Residential_Buildings_009_Cube002_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube003" position={[78.316, 8.327, -282.023]} rotation={[1.486, 0.274, 1.795]} scale={1.704}>
          <mesh name="Residential_Buildings_009_Cube003_1" geometry={nodes.Residential_Buildings_009_Cube003_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube003_2" geometry={nodes.Residential_Buildings_009_Cube003_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube005" position={[8.229, 4.615, -282.356]} rotation={[1.635, -0.23, 1.793]} scale={1.704}>
          <mesh name="Residential_Buildings_009_Cube005_1" geometry={nodes.Residential_Buildings_009_Cube005_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube005_2" geometry={nodes.Residential_Buildings_009_Cube005_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube006" position={[23.161, 6.983, -403.105]} rotation={[1.511, 0.166, 1.79]} scale={[1.884, 1.704, 1.714]}>
          <mesh name="Residential_Buildings_009_Cube006_1" geometry={nodes.Residential_Buildings_009_Cube006_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube006_2" geometry={nodes.Residential_Buildings_009_Cube006_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube007" position={[-7.1, 10.375, -366.869]} rotation={[0.816, -0.243, -2.891]} scale={[1.175, 1.175, 0.519]}>
          <mesh name="Residential_Buildings_009_Cube008_1" geometry={nodes.Residential_Buildings_009_Cube008_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube008_2" geometry={nodes.Residential_Buildings_009_Cube008_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube008" position={[-113.81, 16.118, -339.152]} rotation={[Math.PI / 2, 0, 1.325]} scale={[3.462, 5.792, 3.903]}>
          <mesh name="Residential_Buildings_009_Cube009_1" geometry={nodes.Residential_Buildings_009_Cube009_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube009_2" geometry={nodes.Residential_Buildings_009_Cube009_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube009" position={[50.094, 109.112, -170.547]} rotation={[1.486, 0.274, 1.795]} scale={5.082}>
          <mesh name="Residential_Buildings_009_Cube010_1" geometry={nodes.Residential_Buildings_009_Cube010_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube010_2" geometry={nodes.Residential_Buildings_009_Cube010_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_006_Cube001" position={[-213.983, 88.119, -261.935]} rotation={[Math.PI / 2, 0, 0.192]} scale={[9.021, 9.157, 9.021]}>
          <mesh name="Residential_Buildings_006_Cube001_1" geometry={nodes.Residential_Buildings_006_Cube001_1.geometry} material={materials['ground.005']} />
          <mesh name="Residential_Buildings_006_Cube001_2" geometry={nodes.Residential_Buildings_006_Cube001_2.geometry} material={materials['hotel_glas.005']} />
        </group>
        <group name="Residential_Buildings_009_Cube010" position={[374.628, 52.126, -402.301]} rotation={[-1.701, -0.04, 2.242]} scale={[-5.798, -24.365, -5.814]}>
          <mesh name="Residential_Buildings_009_Cube011_1" geometry={nodes.Residential_Buildings_009_Cube011_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube011_2" geometry={nodes.Residential_Buildings_009_Cube011_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube011" position={[174.919, 122.214, -215.291]} rotation={[1.486, 0.274, 1.795]} scale={5.082}>
          <mesh name="Residential_Buildings_009_Cube012_1" geometry={nodes.Residential_Buildings_009_Cube012_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube012_2" geometry={nodes.Residential_Buildings_009_Cube012_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube012" position={[-34.067, 111.145, -216.283]} rotation={[1.635, -0.23, 1.793]} scale={5.082}>
          <mesh name="Residential_Buildings_009_Cube013_1" geometry={nodes.Residential_Buildings_009_Cube013_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube013_2" geometry={nodes.Residential_Buildings_009_Cube013_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube013" position={[10.458, 118.206, -576.33]} rotation={[1.511, 0.166, 1.79]} scale={[5.619, 5.082, 5.112]}>
          <mesh name="Residential_Buildings_009_Cube014_1" geometry={nodes.Residential_Buildings_009_Cube014_1.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube014_2" geometry={nodes.Residential_Buildings_009_Cube014_2.geometry} material={materials['hotel_glas.003']} />
        </group>
        <group name="Residential_Buildings_009_Cube014" position={[-79.775, 106.951, -468.282]} rotation={[1.854, -0.743, -1.165]} scale={[6.772, 6.772, 2.994]}>
          <mesh name="Residential_Buildings_009_Cube015" geometry={nodes.Residential_Buildings_009_Cube015.geometry} material={materials['ground.003']} />
          <mesh name="Residential_Buildings_009_Cube015_1" geometry={nodes.Residential_Buildings_009_Cube015_1.geometry} material={materials['hotel_glas.003']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cityhall.glb')
