/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/SCENE.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/SCENE.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model001" position={[21.492, -4.453, -40.551]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="656f456211ad484d80aa4a0f34fd2a71fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="Cables" rotation={[-Math.PI / 2, 0, 0]} />
              <group name="Left" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Left_2_0" geometry={nodes.Left_2_0.geometry} material={nodes.Left_2_0.material} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model002" position={[189.462, -12.107, 24.402]} rotation={[1.569, 0, -0.007]}>
          <group name="519572b95b17448f8e0866ef25733d10fbx" rotation={[Math.PI, 0, 0]}>
            <group name="RootNode002">
              <group name="base_cell002" rotation={[1.936, -0.668, 0.256]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model003" position={[7.59, -5.762, 42.461]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="7d60b6d7853149eebaa49a9b7ce0d376fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group name="big_concrete" position={[-16.344, 18.623, -15.308]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="big_concrete__0" geometry={nodes.big_concrete__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="body_balcon" rotation={[-Math.PI / 2, 0, 0]} />
              <group name="body_balcony" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="body_balcony__0" geometry={nodes.body_balcony__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="body_fames" position={[0.001, 14.793, -1.512]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="body_fames__0" geometry={nodes.body_fames__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="body_panels" position={[0.001, 16.875, -1.534]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="body_panels__0" geometry={nodes.body_panels__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="body_slabs" position={[0.001, 10.41, -0.109]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="body_slabs__0" geometry={nodes.body_slabs__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="body_walls" position={[0.001, 15.341, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="body_walls__0" geometry={nodes.body_walls__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="body_windows" position={[0.001, 16.875, -1.49]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="body_windows__0" geometry={nodes.body_windows__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="concrete_debris" position={[3.047, 13.844, 7.63]} rotation={[1.671, -1.535, -0.402]}>
                <mesh name="concrete_debris__0" geometry={nodes.concrete_debris__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="door_cover" position={[-16.453, 5.432, 22.305]} rotation={[-Math.PI / 2, 0, 0]} />
              <group name="simple_wood" position={[-17.803, 15.964, 0.254]} rotation={[-2.614, -0.138, 0.445]}>
                <mesh name="simple_wood__0" geometry={nodes.simple_wood__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="top" position={[0, 31.091, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="top__0" geometry={nodes.top__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="top_frames" position={[-0.079, 34.438, 8.528]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="top_frames__0" geometry={nodes.top_frames__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="top_panels" position={[-12.132, 34.274, 0.266]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="top_panels__0" geometry={nodes.top_panels__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="top_roof" position={[-0.079, 38.986, 8.528]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="top_roof__0" geometry={nodes.top_roof__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="top_slabs" position={[-0.079, 30.658, 8.528]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="top_slabs__0" geometry={nodes.top_slabs__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="top_vent" position={[31.568, 40.26, 8.445]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="top_vent__0" geometry={nodes.top_vent__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="top_walls" position={[-0.079, 34.931, 8.528]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="top_walls__0" geometry={nodes.top_walls__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="top_windows" position={[-0.079, 35.534, 8.528]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="top_windows__0" geometry={nodes.top_windows__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="vertical_concrete" position={[-34.187, 28.756, 15.614]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="vertical_concrete__0" geometry={nodes.vertical_concrete__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="wood_doors" position={[-17.101, 14.598, -0.784]} rotation={[Math.PI / 2, 0, -1.524]}>
                <mesh name="wood_doors__0" geometry={nodes.wood_doors__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="wood_pant" position={[-16.348, 12.084, 0.888]} rotation={[0.225, 0, -1.573]}>
                <mesh name="wood_pant__0" geometry={nodes.wood_pant__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="wooden_cabinet" position={[-16.296, 12.415, 0.181]} rotation={[0.149, 0, -1.574]}>
                <mesh name="wooden_cabinet__0" geometry={nodes.wooden_cabinet__0.geometry} material={materials['Scene_-_Root']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[86.522, 9.449, 52.199]} rotation={[-Math.PI / 2, 0, 1.612]}>
          <group name="destroyed_building_3fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode005">
              <group name="pCube1" position={[0, 6.339, -0.626]}>
                <mesh name="pCube1_lambert2_0" geometry={nodes.pCube1_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCube10" position={[0, 6.339, 67.622]}>
                <mesh name="pCube10_lambert2_0" geometry={nodes.pCube10_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCube11" position={[32.507, 20.099, 41.677]}>
                <mesh name="pCube11_lambert2_0" geometry={nodes.pCube11_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCube12" position={[32.507, -3.658, 41.677]}>
                <mesh name="pCube12_lambert2_0" geometry={nodes.pCube12_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCube13" position={[20.245, 6.339, 32.32]}>
                <mesh name="pCube13_lambert2_0" geometry={nodes.pCube13_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCube14" position={[20.245, 6.339, 67.622]}>
                <mesh name="pCube14_lambert2_0" geometry={nodes.pCube14_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCube15" position={[20.245, 6.339, -0.626]}>
                <mesh name="pCube15_lambert2_0" geometry={nodes.pCube15_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCube18" position={[35.88, 6.339, -0.812]}>
                <mesh name="pCube18_lambert2_0" geometry={nodes.pCube18_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCube9" position={[0, 6.339, 32.32]}>
                <mesh name="pCube9_lambert2_0" geometry={nodes.pCube9_lambert2_0.geometry} material={materials.lambert2} />
              </group>
              <group name="pCylinder1" position={[-1.367, 28.991, 32.637]}>
                <mesh name="pCylinder1_lambert3_0" geometry={nodes.pCylinder1_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder10" position={[-1.567, 28.991, -1.767]}>
                <mesh name="pCylinder10_lambert3_0" geometry={nodes.pCylinder10_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder11" position={[-1.567, 28.991, -0.127]}>
                <mesh name="pCylinder11_lambert3_0" geometry={nodes.pCylinder11_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder12" position={[-0.303, 28.991, -0.127]}>
                <mesh name="pCylinder12_lambert3_0" geometry={nodes.pCylinder12_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder13" position={[18.802, 28.991, -0.127]}>
                <mesh name="pCylinder13_lambert3_0" geometry={nodes.pCylinder13_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder14" position={[18.802, 28.991, -1.767]}>
                <mesh name="pCylinder14_lambert3_0" geometry={nodes.pCylinder14_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder15" position={[19.88, 28.991, -1.767]}>
                <mesh name="pCylinder15_lambert3_0" geometry={nodes.pCylinder15_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder16" position={[19.88, 28.991, -0.127]}>
                <mesh name="pCylinder16_lambert3_0" geometry={nodes.pCylinder16_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder17" position={[18.886, 28.991, 32.593]}>
                <mesh name="pCylinder17_lambert3_0" geometry={nodes.pCylinder17_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder18" position={[18.886, 28.991, 30.953]}>
                <mesh name="pCylinder18_lambert3_0" geometry={nodes.pCylinder18_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder19" position={[19.88, 28.991, 30.953]}>
                <mesh name="pCylinder19_lambert3_0" geometry={nodes.pCylinder19_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder2" position={[-0.373, 28.991, 32.637]}>
                <mesh name="pCylinder2_lambert3_0" geometry={nodes.pCylinder2_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder20" position={[19.88, 28.991, 32.593]}>
                <mesh name="pCylinder20_lambert3_0" geometry={nodes.pCylinder20_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder21" position={[18.795, 28.991, 68.06]}>
                <mesh name="pCylinder21_lambert3_0" geometry={nodes.pCylinder21_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder22" position={[18.795, 28.991, 66.42]}>
                <mesh name="pCylinder22_lambert3_0" geometry={nodes.pCylinder22_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder23" position={[19.88, 28.991, 66.42]}>
                <mesh name="pCylinder23_lambert3_0" geometry={nodes.pCylinder23_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder24" position={[19.88, 28.991, 68.06]}>
                <mesh name="pCylinder24_lambert3_0" geometry={nodes.pCylinder24_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder3" position={[-0.373, 28.991, 30.997]}>
                <mesh name="pCylinder3_lambert3_0" geometry={nodes.pCylinder3_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder33" position={[34.372, 28.991, -0.374]}>
                <mesh name="pCylinder33_lambert3_0" geometry={nodes.pCylinder33_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder34" position={[34.372, 28.991, -2.014]}>
                <mesh name="pCylinder34_lambert3_0" geometry={nodes.pCylinder34_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder35" position={[35.516, 28.991, -2.014]}>
                <mesh name="pCylinder35_lambert3_0" geometry={nodes.pCylinder35_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder36" position={[35.516, 28.991, -0.374]}>
                <mesh name="pCylinder36_lambert3_0" geometry={nodes.pCylinder36_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder37" position={[17.075, 21.126, 44.803]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder37_lambert3_0" geometry={nodes.pCylinder37_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder39" position={[17.075, 21.126, 50.344]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder39_lambert3_0" geometry={nodes.pCylinder39_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder4" position={[-1.367, 28.991, 30.997]}>
                <mesh name="pCylinder4_lambert3_0" geometry={nodes.pCylinder4_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder40" position={[17.075, 21.126, 55.651]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder40_lambert3_0" geometry={nodes.pCylinder40_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder41" position={[17.075, 21.126, 40]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder41_lambert3_0" geometry={nodes.pCylinder41_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder44" position={[17.075, 21.126, 35.19]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder44_lambert3_0" geometry={nodes.pCylinder44_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder45" position={[17.075, 21.126, 19.012]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder45_lambert3_0" geometry={nodes.pCylinder45_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder46" position={[17.075, 21.126, 24.32]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder46_lambert3_0" geometry={nodes.pCylinder46_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder47" position={[17.075, 21.126, 8.64]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder47_lambert3_0" geometry={nodes.pCylinder47_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder48" position={[17.075, 21.126, 13.948]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder48_lambert3_0" geometry={nodes.pCylinder48_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder49" position={[17.075, 21.126, -3.781]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder49_lambert3_0" geometry={nodes.pCylinder49_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder5" position={[-0.373, 28.991, 66.311]}>
                <mesh name="pCylinder5_lambert3_0" geometry={nodes.pCylinder5_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder51" position={[17.075, -3.461, -3.781]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder51_lambert3_0" geometry={nodes.pCylinder51_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder53" position={[17.075, -3.461, 8.64]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder53_lambert3_0" geometry={nodes.pCylinder53_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder54" position={[17.075, -3.461, 13.948]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder54_lambert3_0" geometry={nodes.pCylinder54_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder56" position={[17.075, -3.461, 24.32]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder56_lambert3_0" geometry={nodes.pCylinder56_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder57" position={[17.075, -3.461, 29.883]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder57_lambert3_0" geometry={nodes.pCylinder57_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder58" position={[17.075, -3.461, 35.19]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder58_lambert3_0" geometry={nodes.pCylinder58_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder59" position={[17.075, -3.461, 40]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder59_lambert3_0" geometry={nodes.pCylinder59_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder6" position={[-1.458, 28.991, 66.311]}>
                <mesh name="pCylinder6_lambert3_0" geometry={nodes.pCylinder6_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder61" position={[17.075, -3.461, 50.344]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder61_lambert3_0" geometry={nodes.pCylinder61_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder62" position={[17.075, -3.461, 55.651]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder62_lambert3_0" geometry={nodes.pCylinder62_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder64" position={[17.075, -3.461, 66.311]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder64_lambert3_0" geometry={nodes.pCylinder64_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder65" position={[17.075, 21.126, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder65_lambert3_0" geometry={nodes.pCylinder65_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder66" position={[6.319, 21.126, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder66_lambert3_0" geometry={nodes.pCylinder66_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder67" position={[30.406, 21.126, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder67_lambert3_0" geometry={nodes.pCylinder67_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder68" position={[30.406, -3.484, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder68_lambert3_0" geometry={nodes.pCylinder68_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder69" position={[17.075, -3.484, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder69_lambert3_0" geometry={nodes.pCylinder69_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder7" position={[-1.458, 28.991, 67.951]}>
                <mesh name="pCylinder7_lambert3_0" geometry={nodes.pCylinder7_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder70" position={[6.319, -3.484, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder70_lambert3_0" geometry={nodes.pCylinder70_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder71" position={[11.891, -3.484, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder71_lambert3_0" geometry={nodes.pCylinder71_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder72" position={[11.891, 21.126, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder72_lambert3_0" geometry={nodes.pCylinder72_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder73" position={[24.471, -3.484, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder73_lambert3_0" geometry={nodes.pCylinder73_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder74" position={[24.471, 21.126, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder74_lambert3_0" geometry={nodes.pCylinder74_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder75" position={[17.075, 21.126, 64.493]} rotation={[0, 0, 1.552]}>
                <mesh name="pCylinder75_lambert3_0" geometry={nodes.pCylinder75_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder76" position={[1.688, 21.126, 33.15]} rotation={[1.571, 1.552, 0]}>
                <mesh name="pCylinder76_lambert3_0" geometry={nodes.pCylinder76_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder8" position={[-0.373, 28.991, 67.951]}>
                <mesh name="pCylinder8_lambert3_0" geometry={nodes.pCylinder8_lambert3_0.geometry} material={materials.lambert3} />
              </group>
              <group name="pCylinder9" position={[-0.303, 28.991, -1.767]}>
                <mesh name="pCylinder9_lambert3_0" geometry={nodes.pCylinder9_lambert3_0.geometry} material={materials.lambert3} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model006" position={[249.466, -25.632, -37.895]} rotation={[-1.543, -0.059, -3.108]}>
          <group name="DestroyObyektfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode006">
              <group name="DestroyObyect" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="DestroyObyect_����������������_" geometry={nodes['DestroyObyect_����������������_'].geometry} material={nodes['DestroyObyect_����������������_'].material} position={[175.969, -48.647, 23.822]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model007" position={[-75.651, -4.453, 35.218]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="SOUND_GROUNDSTEAK_INDOORobjcleanermaterialmergergles">
            <mesh name="Object_10001" geometry={nodes.Object_10001.geometry} material={materials.Color_007_1} />
            <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Color_007_1} />
            <mesh name="Object_12001" geometry={nodes.Object_12001.geometry} material={materials.Color_007_1} />
            <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Color_007_1} />
            <mesh name="Object_14001" geometry={nodes.Object_14001.geometry} material={nodes.Object_14001.material} />
            <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
            <mesh name="Object_15001" geometry={nodes.Object_15001.geometry} material={nodes.Object_15001.material} position={[46.723, 62.836, 0.086]} rotation={[0, 0, 0.343]} />
            <mesh name="Object_16001" geometry={nodes.Object_16001.geometry} material={materials.Color_009_1} />
            <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
            <mesh name="Object_18001" geometry={nodes.Object_18001.geometry} material={materials.logo_ws_design_01} />
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Color_007} />
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.Color_008} />
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Color_B25} />
            <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
            <mesh name="Object_6001" geometry={nodes.Object_6001.geometry} material={materials.M_0111_SlateGray} />
            <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.M_0116_Lavender} />
            <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials.M_718S_Terminal} />
            <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Wood_Cherry_Original} />
          </group>
        </group>
        <group name="Sketchfab_model008" position={[-83.173, -4.639, 16.415]} rotation={[-Math.PI / 2, 0, -0.861]}>
          <group name="d0fed21a83c742cebc90b0d9b4b74cc7fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode007" />
          </group>
        </group>
        <group name="Sketchfab_model009" position={[21.492, 77.595, 4.774]} rotation={[-Math.PI, 0, 0]}>
          <group name="meshobjcleaner001" />
        </group>
        <group name="Sketchfab_model010" position={[-138.801, -4.453, -20.728]} rotation={[-Math.PI / 2, 0, 0.801]}>
          <group name="5fe29eb104c246c29ed528bce620fe61fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode008">
              <group name="barrier_LP001_Plane001" rotation={[-Math.PI / 2, 0, 0]} />
              <group name="barrier_LP001_Plane007" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="traffic_cone" position={[21.492, -0.966, 3.885]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh name="traffic_cone_traffic_cone_0" geometry={nodes.traffic_cone_traffic_cone_0.geometry} material={nodes.traffic_cone_traffic_cone_0.material} position={[-71.104, 5.135, 0]} />
        </group>
        <group name="Sketchfab_model012" position={[-128.238, -4.453, -0.249]} rotation={[-Math.PI / 2, 0, 2.038]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Fence-Barricade_02_0" rotation={[Math.PI / 2, 0, 0]}>
                <mesh name="baricade" geometry={nodes.baricade.geometry} material={nodes.baricade.material} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model" position={[5.784, -1.48, -22.312]} rotation={[-Math.PI / 2, 0, 0]} scale={1.062}>
          <group name="Building01fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="Building01" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building01_Building01_0" geometry={nodes.Building01_Building01_0.geometry} material={nodes.Building01_Building01_0.material} />
              </group>
              <group name="Circle" position={[75.993, 63.017, 141.521]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Circle_Building01_0" geometry={nodes.Circle_Building01_0.geometry} material={materials.Building01} scale={0.899} />
              </group>
              <group name="Cube" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_Building01_0" geometry={nodes.Cube_Building01_0.geometry} material={materials.Building01} />
              </group>
              <group name="Cube001" position={[96.338, 13, 134.741]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube001_Building01_0" geometry={nodes.Cube001_Building01_0.geometry} material={materials.Building01} />
              </group>
              <group name="Plane002" position={[93.808, 170.068, 123.361]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Plane_Building01_0" geometry={nodes.Plane_Building01_0.geometry} material={materials.Building01} />
              </group>
              <group name="Plane003" position={[96.338, 13, 137.795]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model013" position={[0, 0, -9.249]} rotation={[-Math.PI / 2, 0, 0]} scale={6.364}>
          <group name="Building01fbx001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode010">
              <group name="Building01001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Building01_Building01_0001" geometry={nodes.Building01_Building01_0001.geometry} material={nodes.Building01_Building01_0001.material} position={[26.591, 5.997, 0]} scale={1.357} />
              </group>
              <group name="Cube002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[145.396, 0, -36.176]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cylinder_1" position={[46.2, 0.262, 27.853]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-5.351, -0.25, -5.351]}>
                <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={nodes.Object_4001.material} position={[17.596, 1.229, 0.058]} scale={2.409} />
                <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['Material.007']} position={[17.596, 1.229, 0.058]} scale={2.409} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model011" position={[192.657, 1.947, -10.431]} rotation={[-Math.PI / 2, 0, 0]} scale={2.821}>
          <group name="statue_lowobjcleanermaterialmergergles">
            <mesh name="torso" geometry={nodes.torso.geometry} material={nodes.torso.material} position={[48.496, 33.199, -0.148]} rotation={[0, 0, -1.939]} scale={2.409} />
          </group>
        </group>
        <group name="Sketchfab_model014" position={[-110.051, -4.422, -17.45]} rotation={[-Math.PI / 2, 0, -1.271]} scale={10.041}>
          <group name="root002">
            <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
              <group name="material_0" rotation={[Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="NurbsPath" position={[7.762, 21.894, -15.499]} />
        <group name="layerbody" position={[292.395, 0, -1.7]} rotation={[-Math.PI / 2, 0, -0.857]} scale={0.144}>
          <group name="ulpper_body" position={[-83.285, -14.253, -0.738]}>
            <group name="body">
              <mesh name="Object_3001" geometry={nodes.Object_3001.geometry} material={materials['Scene_-_Root.002']} />
              <mesh name="Object_4002" geometry={nodes.Object_4002.geometry} material={materials['Scene_-_Root.002']} />
              <mesh name="Object_5002" geometry={nodes.Object_5002.geometry} material={materials['Scene_-_Root.002']} />
            </group>
          </group>
        </group>
        <group name="building" position={[219.307, -16.041, 33.294]} rotation={[1.569, 0, -0.007]} scale={1.575}>
          <group name="519572b95b17448f8e0866ef25733d10fbx001" rotation={[-Math.PI, 0, 0]}>
            <group name="RootNode004">
              <group name="base_cell001" rotation={[1.936, -0.668, 0.256]} scale={0.791}>
                <mesh name="base_cell002_concrete_0" geometry={nodes.base_cell002_concrete_0.geometry} material={nodes.base_cell002_concrete_0.material} />
              </group>
            </group>
          </group>
        </group>
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[-256.416, 3.797, -15.499]} rotation={[-2.57, -1.557, -2.57]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-104.569, -4.366, -19.859]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-67.78, -4.286, 3.377]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[12.91, -3.858, -36.754]} scale={[2.525, 1, 1]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[46.821, 8.323, 30.153]} rotation={[1.576, 0, 0]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[-2.913, 8.612, 28.721]} rotation={[1.641, 0, 0]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.004']} position={[-3.642, 2.943, 0.72]} scale={[0.576, 1, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/SCENE.glb')
