/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/portal.glb -o src/components/PortalFrame.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'CameraAction.001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    PortalMask_Exit: THREE.Mesh
  }
  materials: {
    ['TileWhite.001']: THREE.MeshStandardMaterial
    ['TileBlack.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/portal.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NurbsPath" position={[0, 2.21, -5.328]} />
        <pointLight name="Point" intensity={27613.284} decay={2} position={[301.602, 174.698, -11.821]} rotation={[-Math.PI / 2, 0, 0]} />
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[339.647, 176.928, -5.328]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
        <group name="Cylinder" position={[-4.362, 180.665, -5.802]} rotation={[0, 0, -1.587]} scale={-25.861}>
          <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['TileWhite.001']} />
          <mesh name="Cylinder001_2" geometry={nodes.Cylinder001_2.geometry} material={materials['TileBlack.001']} />
        </group>
        <group name="Cylinder001" position={[177.311, 177.391, -5.802]} rotation={[0, 0, -1.587]} scale={-25.861}>
          <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['TileWhite.001']} />
          <mesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={materials['TileBlack.001']} />
        </group>
        <mesh name="PortalMask_Exit" geometry={nodes.PortalMask_Exit.geometry} material={nodes.PortalMask_Exit.material} position={[-90.982, 181.886, -7.819]} rotation={[-0.09, 0, -1.57]} scale={19.649} />
      </group>
    </group>
  )
}

useGLTF.preload('/portal.glb')
